codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      board:
        target: 90%
        threshold: 0%
        paths: "pkg/chessai/board"
      default: true
    patch:
      board:
        target: 100%
        paths: "pkg/chessai/board"
      default: false  # TODO(Vadim) add this when we have more tests before going public
    changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
