language: go

go:
  - 1.12.x

#install:
#  - go get -v golang.org/x/lint/golint

script:
  #  - golint -set_exit_status ./...
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
