language: go
go: 1.12.x
# script: go test -v test
notifications:
  email: false

script:
  - go test test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 673838c5-c100-44ca-8fde-697a1aafc025