codecov:
  notify:
    require_ci_to_pass: yes
#  strict_yaml_branch: master # TODO(Vadim) add this when we have more tests before going public

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      board: # board should have 90 percent cov with always increasing
        target: 90%
        threshold: 0%
        paths: "pkg/chessai/board"
      default: yes
    patch:
      board: # board diff should have 95 percent cov
        target: 95%
        paths: "pkg/chessai/board"
      default: false
    #        TODO(Vadim) add this when we have more tests before going public
    #        target: auto
    #        threshold: 3%
    changes: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
